openapi: "3.0.0"
info:
  version: 1.0.0
  title: Nurse Scheduling
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /schedule:
    post:
      requestBody:
        description: A list of workers and shifts
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/scheduleRequest'
      responses:
        '200':
          description: A matching and suboptimal status
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/scheduleResponse"
components:
  schemas:
    worker:
      required:
        - id
        - availability
        - payrate
      properties:
        id:
          type: integer
          format: int64
        availability:
          type: array
          items:
            $ref: "#/components/schemas/day"
        payrate:
          type: number
          format: float64
    workers:
      type: array
      items:
        $ref: "#/components/schemas/worker"
      minItems: 1
    day:
      type: string
      enum:
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
        - Saturday
        - Sunday
    shift:
      required:
        - id
        - day
      properties:
        id:
          type: integer
          format: int64
        day:
          type: array
          items:
            $ref: '#/components/schemas/day'
          minItems: 1
          maxItems: 1
    shifts:
      type: array
      items:
        $ref: "#/components/schemas/shift"
      minItems: 1
    match:
      required:
      - workerId
      - shiftId
      properties:
        workerId:
          type: integer
          format: int64
        shiftId:
          type: integer
          format: int64
    scheduleRequest:
      required:
        - workers
        - shifts
      properties:
        workers:
            $ref: "#/components/schemas/workers"
        shifts:
          $ref: "#/components/schemas/shifts"
    matching:
      type: array
      items:
        $ref: "#/components/schemas/match"
    scheduleResponse:
      required:
        - matching
        - suboptimal
      properties:
        matching:
            $ref: "#/components/schemas/matching"
        suboptimal:
          type: boolean
          format: boolean
