name: Checkstyle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run java checkstyle
        uses: nikitasavinov/checkstyle-action@0.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
