# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [ 'zulu', 'adopt' ]
        java: [ '8', '11', '13', '15' ]
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting (sonarqube)
          fetch-depth: 0
      - name: Install native ORTools libraries
        run: |
          sudo wget https://github.com/oliviercailloux/google-or-tools-java/raw/master/lib/libortools.so -P /usr/lib64
          sudo wget https://github.com/oliviercailloux/google-or-tools-java/raw/master/lib/libjniortools.so -P /usr/lib64
      - name: Set up JDK ${{ matrix.Java }} (${{ matrix.distribution }})
        uses: actions/setup-java@v3.13.0
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report
      - name: Sonarqube
        if: matrix.java == '11' && matrix.distribution == 'zulu'
        run: mvn sonar:sonar -Dsonar.projectKey=com.mercuriete:java-nurse-scheduling-problem -Dsonar.organization=mercuriete-github -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
